// Behaviour test for the Home page, with screenshots. Run after a build. node scripts/quality/check-home.mjs [--dir=dist]
import fs from 'node:fs';
import { serve, launch, arg } from '../lib.mjs';
fs.mkdirSync('reports/home', { recursive: true });
const server = await serve(arg('dir', 'dist'), 4493), browser = await launch(), O = 'http://127.0.0.1:4493', out = {};
const open = async (path, { width = 1280, height = 720, js = true } = {}) => { const ctx = await browser.newContext({ viewport: { width, height }, reducedMotion: 'reduce', javaScriptEnabled: js }); const hosts = new Set(); ctx.on('request', r => { const h = new URL(r.url()).host; if (!h.startsWith('127.0.0.1')) hosts.add(h); }); await ctx.route(u => !u.hostname.startsWith('127.0.0.1'), r => r.abort()); const p = await ctx.newPage(); await p.goto(O + path, { waitUntil: 'load' }); await p.waitForTimeout(500); return { ctx, p, hosts }; };

{ const { ctx, p, hosts } = await open('/?theme=light');
  out.sections = await p.evaluate(() => [...document.querySelectorAll('main > section, main > [data-home-feed]')].map(s => `${s.id}: ${s.querySelector('h1, h2')?.textContent.trim().replace(/\s+/g, ' ').slice(0, 50)} [${getComputedStyle(s).backgroundColor === 'rgba(0, 0, 0, 0)' ? 'page' : 'card'}]`));
  out.headings = await p.evaluate(() => { const hs = [...document.querySelectorAll('main h1, main h2, main h3, main h4')].map(h => +h.tagName[1]); return { h1: hs.filter(x => x === 1).length, skips: hs.filter((h, i) => i > 0 && h - hs[i - 1] > 1).length, outline: hs.join('') }; });
  out.hero = await p.evaluate(() => ({ badge: document.querySelector('#top [data-badge]')?.textContent.trim(), lead: document.querySelector('#top p[data-hero-el]')?.textContent.trim().slice(0, 60), workedWith: [...document.querySelectorAll('#top ul:not([data-hero-stack]) > li')].map(l => l.textContent.trim()), primaryButtons: document.querySelectorAll('#top [data-ds-button="primary"]').length, resume: (() => { const a = [...document.querySelectorAll('#top a')].find(x => /resume/i.test(x.textContent)); return a && { text: a.textContent.trim().replace(/\s+/g, ' '), href: a.getAttribute('href').slice(0, 40), target: a.target }; })() }));
  // The deck: cards from the collection, the counter, the arrows, keyboard
  const deck = () => p.evaluate(() => ({ counter: document.querySelector('#top bdi[aria-live]')?.textContent.trim(), front: (() => { const c = document.querySelector('[data-stack-card][data-pos="0"]'); return c && { title: c.querySelector('a').textContent.replace(/\s+/g, ' ').trim().slice(0, 60), href: c.querySelector('a').getAttribute('href'), hidden: c.getAttribute('aria-hidden'), tabindex: c.querySelector('a').getAttribute('tabindex') }; })(), reachable: [...document.querySelectorAll('[data-stack-card] a')].filter(a => a.tabIndex === 0).length }));
  out.deckStart = { cards: await p.evaluate(() => [...document.querySelectorAll('[data-stack-card]')].map(c => ({ pos: c.dataset.pos, href: c.querySelector('a').getAttribute('href'), img: (c.querySelector('img')?.getAttribute('src') || '').slice(0, 40), srcset: !!c.querySelector('img')?.getAttribute('srcset') }))), ...(await deck()) };
  await p.locator('button[aria-label="Next case study"]').focus(); await p.keyboard.press('Enter'); await p.waitForTimeout(700); out.deckAfterNext = await deck();
  await p.keyboard.press('Enter'); await p.waitForTimeout(700); out.deckAfterNextTwice = await deck();
  await p.locator('button[aria-label="Previous case study"]').click(); await p.waitForTimeout(700); out.deckAfterPrevious = await deck();
  await p.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 500) { scrollTo(0, y); await new Promise(r => setTimeout(r, 80)); } scrollTo(0, 0); }); await p.waitForTimeout(700);
  out.images = await p.evaluate(() => [...document.images].map(i => ({ src: (i.currentSrc || i.src).replace(location.origin, '').slice(0, 50), loaded: i.complete && i.naturalWidth > 0, alt: i.getAttribute('alt'), loading: i.loading })));
  out.thirdPartyHosts = [...hosts];
  out.text = await p.evaluate(() => { const t = document.querySelector('main').innerText; return { latitude: /Latitude/.test(t), percents: t.match(/[+-]?\d+%/g) || [], oldTitle: /Lead product designer|AI-first/i.test(t), placeholders: /\[VERIFY\]|\[METRIC/.test(t), emails: [...new Set(t.match(/[\w.+-]+@[\w-]+\.\w+/g) || [])], linkedinInMain: document.querySelectorAll('main a[href*="linkedin.com/in/"]').length }; });
  out.closing = await p.evaluate(() => [...document.querySelectorAll('#contact a')].map(a => `${a.textContent.trim().replace(/\s+/g, ' ').slice(0, 45)} -> ${a.getAttribute('href').slice(0, 50)}`));
  await p.screenshot({ path: 'reports/home/home-1280-light.png', fullPage: true }); await ctx.close(); }
for (const [w, h, theme] of [[390, 844, 'dark'], [320, 568, 'light'], [768, 1024, 'light']]) { const { ctx, p } = await open(`/?theme=${theme}`, { width: w, height: h }); out[`at ${w}`] = await p.evaluate(() => ({ pageScrolls: document.documentElement.scrollWidth > innerWidth, h1InFirstView: document.querySelector('h1').getBoundingClientRect().bottom <= innerHeight })); await p.screenshot({ path: `reports/home/home-${w}-${theme}.png`, fullPage: true }); await ctx.close(); }
{ const { ctx, p } = await open('/', { js: false }); out.noJs = await p.evaluate(() => ({ cardsInPage: document.querySelectorAll('[data-stack-card] a').length, mainChars: document.querySelector('main').innerText.length })); await ctx.close(); }
await browser.close(); server.close();
fs.writeFileSync('reports/home/check-home.json', JSON.stringify(out, null, 2)); console.log(JSON.stringify(out, null, 2));
