// Spot-check of claims made in earlier phase reports and in docs/AUDIT_FINDINGS.md (Phase 15). Each claim is measured
// again from scratch on the current build; nothing is read from an earlier report.
// node scripts/quality/verify-claims.mjs [--dir=dist]   (quality build)   -> reports/verify/claims.json
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, serve, launch, arg } from '../lib.mjs';

const PORT = 4421, O = `http://127.0.0.1:${PORT}`, server = await serve(arg('dir', 'dist'), PORT), browser = await launch(), claims = [];
const claim = (id, text, holds, measured) => { claims.push({ id, claim: text, holds, measured }); console.log(`${holds ? 'HOLDS ' : 'FAILS '} ${id}: ${text}\n        measured: ${typeof measured === 'string' ? measured : JSON.stringify(measured)}`); };
const open = async (route, o = {}) => { const ctx = await browser.newContext({ viewport: { width: o.width || 1280, height: o.height || 720 }, reducedMotion: 'reduce', javaScriptEnabled: o.js !== false, hasTouch: !!o.touch }); const hosts = new Set(); ctx.on('request', r => { const h = new URL(r.url()).host; if (!h.startsWith('127.0.0.1')) hosts.add(h); }); await ctx.route(u => !u.hostname.startsWith('127.0.0.1'), r => r.abort()); const p = await ctx.newPage(); await p.goto(O + route, { waitUntil: 'load' }); await p.waitForTimeout(400); return { ctx, p, hosts }; };

{ const { ctx, p } = await open('/?theme=dark'); const c = await p.evaluate(() => ({ body: getComputedStyle(document.body).color, token: getComputedStyle(document.documentElement).getPropertyValue('--text-body').trim() })); claim('M-02', 'Dark theme body text is rgb(222, 228, 236), not white', c.body === 'rgb(222, 228, 236)', c); await ctx.close(); }
for (const [route, lang] of [['/', 'English'], ['/ar', 'Arabic']]) { const { ctx, p } = await open(route, { width: 320, height: 568 }); const b = await p.evaluate(() => { const m = document.querySelector('[data-menu-button], [aria-controls="site-menu"]'); const r = m.getBoundingClientRect(); return { x: Math.round(r.left), right: Math.round(r.right), w: Math.round(r.width), h: Math.round(r.height), page: document.documentElement.scrollWidth }; }); claim('M-03', `${lang} menu button is fully on screen at 320px and 44px or larger`, b.x >= 0 && b.right <= 320 && b.w >= 44 && b.h >= 44 && b.page <= 320, b); await ctx.close(); }
{ const { ctx, p, hosts } = await open('/'); await p.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 600) { scrollTo(0, y); await new Promise(r => setTimeout(r, 80)); } }); await p.waitForTimeout(600); claim('M-08 / Phase 14', 'Home contacts no third-party host, even after scrolling the whole page', hosts.size === 0, [...hosts]); await ctx.close(); }
{ const { ctx, p } = await open('/', { width: 390, height: 844 }); const btn = p.locator('[aria-controls="site-menu"]').first(); await btn.focus(); await p.keyboard.press('Enter'); await p.waitForTimeout(300);
  const a = await p.evaluate(() => ({ expanded: document.querySelector('[aria-controls="site-menu"]').getAttribute('aria-expanded'), focusIn: !!document.activeElement.closest('#site-menu, [data-site-header]'), focusName: (document.activeElement.getAttribute('aria-label') || document.activeElement.textContent).trim().slice(0, 30), inert: document.querySelectorAll('[inert]').length }));
  let escaped = 0; for (let i = 0; i < 30; i++) { await p.keyboard.press('Tab'); if (!(await p.evaluate(() => !!document.activeElement.closest('#site-menu, [data-site-header]')))) escaped++; }
  await p.keyboard.press('Escape'); await p.waitForTimeout(200); const z = await p.evaluate(() => ({ expanded: document.querySelector('[aria-controls="site-menu"]').getAttribute('aria-expanded'), focusBack: document.activeElement.getAttribute('aria-controls') === 'site-menu' }));
  claim('M-18', 'Mobile menu: opens from the keyboard, traps focus, Escape closes and returns focus to the button', a.expanded === 'true' && a.focusIn && escaped === 0 && z.expanded === 'false' && z.focusBack, { ...a, tabStopsOutsideMenu: escaped, afterEscape: z }); await ctx.close(); }
{ const counts = {}; for (const r of ['/', '/services', '/blog', '/case-studies/colaberry-design-system', '/about', '/contact']) { const { ctx, p } = await open(r); counts[r] = await p.evaluate(() => { const c = {}; for (const s of document.querySelectorAll('svg[stroke-width], svg [stroke-width]')) { const w = s.getAttribute('stroke-width'); c[w] = (c[w] || 0) + 1; } return c; }); await ctx.close(); }
  claim('M-26', 'Icon stroke width is 1.75 everywhere, none at 2', Object.values(counts).every(c => !c['2']), counts); }
{ const r = {}; for (const route of ['/', '/case-studies/colaberry-design-system', '/writing', '/blog/rich-content-fixture']) { const { ctx, p } = await open(route, { js: false }); r[route] = await p.evaluate(() => ({ chars: document.querySelector('main').innerText.length, rawPlaceholders: (document.body.innerText.match(/\{\{|\}\}/g) || []).length, navLinks: document.querySelectorAll('nav a').length, description: !!document.querySelector('meta[name=description]')?.content, hiddenContent: [...document.querySelectorAll('main [data-reveal], main [data-reveal-group] > *')].filter(e => getComputedStyle(e).opacity === '0').length })); await ctx.close(); }
  claim('M-07', 'With JavaScript off the pages still show their content and navigation, with nothing left invisible', Object.values(r).every(x => x.chars > 1500 && x.rawPlaceholders === 0 && x.navLinks > 5 && x.hiddenContent === 0), r); }
{ const { ctx, p } = await open('/blog/component-spec-files?theme=light', { width: 320, height: 568 }); const c = await p.evaluate(() => { const pre = [...document.querySelectorAll('pre')].map(e => ({ overflowX: getComputedStyle(e).overflowX, scroll: e.scrollWidth, client: e.clientWidth, right: Math.round(e.getBoundingClientRect().right) })); return { page: document.documentElement.scrollWidth, pre }; }); claim('M-15', 'Guide code blocks stay inside a 320px page', c.page <= 320 && c.pre.every(x => x.right <= 320), c); await ctx.close(); }
{ let n = 0, pages = 0; for (const f of fs.readdirSync(path.join(ROOT, arg('dir', 'dist')), { recursive: true }).filter(f => String(f).endsWith('.html'))) { pages++; n += (fs.readFileSync(path.join(ROOT, arg('dir', 'dist'), String(f)), 'utf8').match(/<image-slot/g) || []).length; } claim('M-05', 'No image-slot element is left in any built page', n === 0, { pages, imageSlots: n }); }
{ const { ctx, p } = await open('/', { touch: true, width: 390, height: 844 }); const sel = 'main [data-ds-button="secondary"], main .ui-button-secondary'; const before = await p.evaluate(s => { const e = document.querySelector(s); const c = getComputedStyle(e); return c.backgroundColor + ' ' + c.transform; }, sel); const hoverMedia = await p.evaluate(() => matchMedia('(hover: hover)').matches); claim('M-16', 'On a touch screen, hover styles do not apply (hover rules sit behind @media (hover: hover))', hoverMedia === false, { hoverMediaMatches: hoverMedia, restStyle: before }); await ctx.close(); }
{ const { ctx, p } = await open('/'); const c = await p.evaluate(() => { const badges = [...document.querySelectorAll('[data-badge], .ui-badge')]; return { badges: badges.length, nowrap: badges.filter(b => getComputedStyle(b).whiteSpace === 'nowrap').length }; }); const s = await open('/_states', { width: 320, height: 640 }); const st = await s.p.evaluate(() => ({ scroll: document.documentElement.scrollWidth, badgesOff: [...document.querySelectorAll('[data-badge], .ui-badge')].filter(b => b.getBoundingClientRect().right > innerWidth + 1).length })); claim('M-14', 'Badges wrap, and the 60-character fixture causes no sideways scroll at 320px', c.nowrap === 0 && st.scroll <= 320 && st.badgesOff === 0, { home: c, statesAt320: st }); await ctx.close(); await s.ctx.close(); }
{ const r = {}; for (const route of ['/', '/work', '/blog/rich-content-fixture', '/about', '/ar']) { const { ctx, p } = await open(route); r[route] = await p.evaluate(() => ({ canonical: document.querySelector('link[rel=canonical]')?.href, hreflang: [...document.querySelectorAll('link[hreflang]')].map(l => l.hreflang) })); await ctx.close(); } claim('M-24 / Phase 13', 'Every page has a canonical link; the two bilingual pages name each other with hreflang', Object.values(r).every(x => x.canonical) && r['/'].hreflang.includes('ar') && r['/ar'].hreflang.includes('en'), r); }
{ const { ctx, p } = await open('/case-studies/full-fixture'); const c = await p.evaluate(() => ({ metricTiles: document.querySelectorAll('.case-metrics li').length, tiles: [...document.querySelectorAll('.case-metrics li')].map(l => l.textContent.trim().slice(0, 30)) })); const real = await open('/case-studies/colaberry-design-system'); const m = await real.p.evaluate(() => ({ metricTiles: document.querySelectorAll('.case-metrics li').length, percents: (document.querySelector('main').innerText.match(/[+-]?\d+%/g) || []) })); claim('Phase 9', 'A case study shows a metric as a figure only when it is marked verified (the three real case studies have none verified)', m.metricTiles === 0, { fullFixture: c, colaberry: m }); await ctx.close(); await real.ctx.close(); }
{ const { ctx, p } = await open('/about'); const c = await p.evaluate(() => ({ percents: document.querySelector('main').innerText.match(/[+-]?\d+%/g) || [], placeholders: /\[VERIFY\]|\[METRIC/.test(document.body.innerText), formOnContact: null })); claim('Phase 12', 'About shows no unverified percentage and no placeholder', c.percents.length === 0 && !c.placeholders, c); await ctx.close(); }
{ const { ctx, p } = await open('/'); const c = await p.evaluate(() => ({ title: document.title, hero: document.querySelector('[data-hero-el], #top p')?.textContent.trim().slice(0, 90), deckRole: [...document.querySelectorAll('#top *')].map(e => e.childNodes.length === 1 ? e.textContent : '').filter(t => /LEAD PRODUCT DESIGNER|Lead Product Designer/i.test(t)).length, footer: document.querySelector('footer')?.innerText.match(/AI-first [A-Za-z ]+Designer/)?.[0] })); claim('Phase 13 (consistency)', 'The site states one job title everywhere', !/Lead/i.test(c.hero || '') && c.deckRole === 0, c); await ctx.close(); }
{ const { ctx, p } = await open('/contact'); const c = await p.evaluate(() => ({ form: !!document.querySelector('[data-contact-form]'), action: document.querySelector('[data-contact-form] form')?.action })); claim('Phase 12 (note)', 'The contact form in a quality build posts to a fixture address, not a real form', c.form && /formspree\.io\/f\/fixture$/.test(c.action || ''), c); await ctx.close(); }

await browser.close(); server.close();
fs.mkdirSync(path.join(ROOT, 'reports/verify'), { recursive: true }); fs.writeFileSync(path.join(ROOT, 'reports/verify/claims.json'), JSON.stringify(claims, null, 1));
console.log(`\n${claims.filter(c => c.holds).length} of ${claims.length} claims hold`);
