// Measures the evidence for fixed findings on the built site and prints one line per finding.
// node scripts/quality/verify-fixes.mjs   (run after `npm run build`)
import { serve, launch } from '../lib.mjs';
const server = await serve('dist', 4460); const browser = await launch(); const O = 'http://127.0.0.1:4460';
const out = {};
async function page(path, opts = {}, w = 1280, h = 720) { const ctx = await browser.newContext({ viewport: { width: w, height: h }, ...opts }); const p = await ctx.newPage(); await p.goto(O + path, { waitUntil: 'load' }); await p.waitForLoadState('networkidle').catch(() => {}); await p.waitForTimeout(400); return { ctx, p }; }

// M-02: body colour and font size in each theme and language
for (const [k, path] of [['en light', '/?theme=light'], ['en dark', '/?theme=dark'], ['ar dark', '/ar?theme=dark']]) { const { ctx, p } = await page(path); out['M-02 ' + k] = await p.evaluate(() => { const b = getComputedStyle(document.body), r = getComputedStyle(document.documentElement); return `--text-body=${r.getPropertyValue('--text-body').trim()} body colour ${b.color} font-size ${b.fontSize}`; }); await ctx.close(); }
// dark header link hover
{ const { ctx, p } = await page('/about?theme=dark'); const l = p.locator('.header-nav-link').first(); const a = await l.evaluate(e => getComputedStyle(e).color + ' / ' + getComputedStyle(e).textDecorationLine); await l.hover(); await p.waitForTimeout(400); out['M-02/M-17 dark nav link rest -> hover'] = a + ' -> ' + await l.evaluate(e => getComputedStyle(e).color + ' / ' + getComputedStyle(e).textDecorationLine); await ctx.close(); }
// M-03: header controls at 320 in both directions
for (const [k, path] of [['en', '/work'], ['ar', '/ar']]) { const { ctx, p } = await page(path + '?theme=light', {}, 320, 568); out['M-03 header at 320 ' + k] = await p.evaluate(() => [...document.querySelectorAll('[data-site-header] a, [data-site-header] button')].filter(e => e.getClientRects().length).map(e => { const r = e.getBoundingClientRect(); return (e.getAttribute('aria-label') || e.innerText || '').trim().slice(0, 14) + ' ' + Math.round(r.left) + '..' + Math.round(r.right); }).join(' | ')); await ctx.close(); }
// M-04: hero badge box at phone widths
for (const w of [320, 390, 414]) { const { ctx, p } = await page('/?theme=light', {}, w, 800); out['M-04 badge at ' + w] = await p.evaluate(() => { const b = document.querySelector('#top [data-badge]'); if (!b) return 'badge not found'; const r = b.getBoundingClientRect(); return `x ${Math.round(r.left)}..${Math.round(r.right)} of ${innerWidth}, height ${Math.round(r.height)}px, text "${b.innerText.trim().slice(-22)}"`; }); await ctx.close(); }
// M-05, M-06: image editor buttons and alt text
{ const { ctx, p } = await page('/case-studies/colaberry-design-system?theme=light'); out['M-05 editor buttons in DOM'] = await p.evaluate(() => document.querySelectorAll('image-slot').length + ' image-slot elements'); out['M-06 alt text'] = await p.evaluate(() => [...document.querySelectorAll('[data-image-box] img')].map(i => JSON.stringify(i.alt)).join(', ')); await ctx.close(); }
// M-07: JavaScript off
for (const path of ['/', '/case-studies/colaberry-design-system']) { const { ctx, p } = await page(path, { javaScriptEnabled: false }); out['M-07 no-JS ' + path] = await p.evaluate(() => `${document.body.innerText.trim().length} characters, ${(document.body.innerText.match(/\{\{/g) || []).length} raw placeholders, ${document.querySelectorAll('nav a').length} nav links, description ${!!document.querySelector('meta[name=description]')}`); await ctx.close(); }
// M-08, M-11, M-30: external hosts and script weight
{ const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } }); const p = await ctx.newPage(); const hosts = new Set(); let js = 0; p.on('response', async r => { const u = new URL(r.url()); if (u.hostname !== '127.0.0.1') hosts.add(u.hostname); if (/\.js(\?|$)/.test(u.pathname)) { try { js += (await r.body()).length; } catch {} } }); await p.goto(O + '/', { waitUntil: 'load' }); await p.waitForLoadState('networkidle').catch(() => {}); out['M-08/M-11/M-30 Home'] = `external hosts: ${[...hosts].join(', ') || 'none'}; JavaScript files ${(js / 1024).toFixed(1)} KB uncompressed`; await ctx.close(); }
// M-15: code block scrolls inside itself at 320
{ const { ctx, p } = await page('/blog/component-spec-files?theme=light', {}, 320, 568); out['M-15 code block at 320'] = await p.evaluate(() => { const pre = document.querySelector('[data-article] pre'); if (!pre) return 'pre not found'; const s = getComputedStyle(pre); return `overflow-x ${s.overflowX}, scrollWidth ${pre.scrollWidth} in clientWidth ${pre.clientWidth}, page scrollWidth ${document.documentElement.scrollWidth}`; }); await ctx.close(); }
// M-16: touch tap does not leave a hover state
{ const { ctx, p } = await page('/404?theme=light', { hasTouch: true, isMobile: true }, 390, 844); const el = p.locator('main a', { hasText: 'Download resume' }).first(); await el.evaluate(e => e.addEventListener('click', ev => ev.preventDefault())); const a = await el.evaluate(e => getComputedStyle(e).backgroundColor + ' ' + getComputedStyle(e).transform); await el.tap(); await p.waitForTimeout(600); out['M-16 secondary button before -> after tap'] = a + ' -> ' + await el.evaluate(e => getComputedStyle(e).backgroundColor + ' ' + getComputedStyle(e).transform); await ctx.close(); }
// M-18: mobile menu
{ const { ctx, p } = await page('/work?theme=light', { reducedMotion: 'reduce' }, 390, 844); await p.locator('[data-menu-open]').focus(); await p.keyboard.press('Enter'); await p.waitForTimeout(300); const r = await p.evaluate(() => { const m = document.querySelector('[data-menu]'); const cur = m.querySelector('[aria-current="page"]'); return `open ${!m.hidden}, expanded ${document.querySelector('[data-menu-open]').getAttribute('aria-expanded')}, focus on "${document.activeElement.getAttribute('aria-label')}", inert siblings ${document.querySelectorAll('[inert]').length}, scroll lock "${document.documentElement.style.overflow}", current link "${cur ? cur.innerText : 'none'}" underline ${cur ? getComputedStyle(cur).backgroundImage.slice(0, 15) : ''}`; }); let escapes = 0; for (let i = 0; i < 25; i++) { await p.keyboard.press('Tab'); if (!(await p.evaluate(() => document.querySelector('[data-menu]').contains(document.activeElement)))) escapes++; } await p.keyboard.press('Escape'); await p.waitForTimeout(200); out['M-18 mobile menu'] = r + `; Tab escapes ${escapes}/25; after Escape: closed ${await p.evaluate(() => document.querySelector('[data-menu]').hidden)}, focus back on "${await p.evaluate(() => document.activeElement.getAttribute('aria-label'))}"`; await ctx.close(); }
// M-23: theme toggle state and persistence; M-24: titles
{ const { ctx, p } = await page('/about?theme=light'); const b = p.locator('[data-theme-toggle]').first(); const before = await b.evaluate(e => e.getAttribute('aria-pressed') + ' "' + e.getAttribute('aria-label') + '"'); await b.click(); await p.waitForTimeout(300); out['M-23 toggle'] = `aria-pressed/label before ${before}; after ${await b.evaluate(e => e.getAttribute('aria-pressed') + ' "' + e.getAttribute('aria-label') + '"')}; data-theme ${await p.evaluate(() => document.documentElement.getAttribute('data-theme'))}; stored ${await p.evaluate(() => localStorage.getItem('aiuxaleem-theme'))}; theme-color ${await p.evaluate(() => document.querySelector('meta[name=theme-color]').content)}`; await ctx.close(); }
{ const titles = []; for (const s of ['colaberry-design-system', 'freight-platform-rebrand', 'ai-ad-reel-pipeline']) { const { ctx, p } = await page('/case-studies/' + s); titles.push(await p.title() + ' [canonical ' + await p.evaluate(() => (document.querySelector('link[rel=canonical]') || {}).href) + ']'); await ctx.close(); } out['M-24 case titles'] = titles.join(' | '); }
// M-26: icon stroke widths across pages
{ const counts = {}; for (const path of ['/', '/services', '/blog', '/case-studies/colaberry-design-system']) { const { ctx, p } = await page(path); const c = await p.evaluate(() => { const m = {}; document.querySelectorAll('svg[stroke-width]').forEach(s => { const k = s.getAttribute('stroke-width'); m[k] = (m[k] || 0) + 1; }); return m; }); for (const [k, v] of Object.entries(c)) counts[k] = (counts[k] || 0) + v; await ctx.close(); } out['M-26 stroke widths (4 pages)'] = JSON.stringify(counts); }
for (const [k, v] of Object.entries(out)) console.log(k + ': ' + v);
await browser.close(); server.close();
